feat(FEC-13718): [Quiz Plugin]: Add Events (used by kava analytics)
kaltura/playkit-js-ivq pull request #121
Opened 2024-03-14 13:48 UTC by JonathanTGold

Add Events (used by kava analytics)

Solves FEC-13718

2024-03-14 13:51 UTC, semarche-kaltura requested changes

2024-03-14 13:51 UTC, semarche-kaltura commented on src/ivq.tsx
> +    console.log('ivqqqq', 'nav-clikc')
console.log

2024-03-17 12:43 UTC, JonathanTGold commented on src/ivq.tsx
> +    console.log('ivqqqq', 'nav-clikc')
fixed

2024-03-18 11:00 UTC, semarche-kaltura approved these changes

2024-03-18 11:07 UTC, merged