fix(FEV-1433): Ensure the visible text label for a control is included in the control's accessible name
kaltura/playkit-js-ivq pull request #79
Opened 2023-03-12 13:20 UTC by lianbenjamin

change "Done" button's text to "Close"

Solves FEV-1433

2023-03-13 10:27 UTC, SivanA-Kaltura requested changes

2023-03-13 10:50 UTC, lianbenjamin commented on translations/en.i18n.json
> +      "close_button": "Close",
@SivanA-Kaltura there's a ticket for the translation

2023-03-13 15:19 UTC, SivanA-Kaltura commented on translations/en.i18n.json
> +      "close_button": "Close",
@lianbenjamin by the way, if the text already exists in the player you can reuse it. 
for example, the text for close exists here:
https://github.com/kaltura/playkit-js-ui/blob/master/translations/en.i18n.json#L51

so you can load it with something like withText({close: 'overlay.close'})

2023-03-13 15:41 UTC, lianbenjamin commented on translations/en.i18n.json
> +      "close_button": "Close",
@semarche-kaltura what do you think about using "overlay.close" from ui repo in ivq plugin?

2023-03-13 15:46 UTC, semarche-kaltura commented on translations/en.i18n.json
> +      "close_button": "Close",
> @semarche-kaltura what do you think about using "overlay.close" from ui repo in ivq plugin?

advantages: we don't need keep new translates (in our case duplicates with `overlay.close`).
disadvantages: if `overlay.close` got changed or if we need specific translate for `close_button` - we'll got the problem.
IMHO - let's keep translates related to IVQ inside IVQ repo

2023-03-13 15:48 UTC, semarche-kaltura requested changes
PR looks good and if we have to deliver changes ASAP - go and merge.
I marked the PR as "Changes needed" only to got increased test coverage. If we're not in rush - cover the changes by e2e tests

2023-03-14 10:10 UTC, semarche-kaltura approved these changes

2023-03-14 10:13 UTC, merged